import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from "next/link"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Exercise PWA APollo GraphQL</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to PWA Apollo GraphQL Exercise!
        </h1>

        <h2>
					<Link href={{pathname: "/categories", query: {title: 'Category List'}}} as={'/categories'}>
						<a>List Categories</a>
					</Link>
				</h2>
        <h2>
					<Link href={{pathname: "/categories/input", query: {title: 'Input Subscribe'}}} as={'/categories/input'}>
						<a>Input Subscribe</a>
					</Link>
				</h2>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>

      <style jsx>{`
        a:link, a:visited {
          background-color: #f44336;
          color: white;
          padding: 14px 25px;
          text-align: center;
          text-decoration: none;
          display: inline-block;
        }
  
        a:hover, a:active {
          background-color: red;
        }
      `}</style>
    </div>
  )
}
